default: &default
  adapter: postgresql
  pool: 64
  timeout: 5000
  username: postgres
  port: 5432

development:
  <<: *default
  database: artapi_dev

test:
  <<: *default
  database: artapi_test

production:
  <<: *default
  database: artapi_prod